blog_theme: gray-yellow
name: cmakara
paginate: 10
url: https://cmakara.github.io

about_enabled: true
# discus_identifier:
ga_analytics: UA-112479545-1
local_fonts: false
rss_enabled: true
scrollappear_enabled: true
social:
  github: cmakara
  linkedin: csabamakara
  email: csaba.makara@booom.studio

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
